export const MENU = {
  ADDONS: 'addOns',
  ADDON_PRODUCTS: 'addOnProducts',
  BUILDINGS: 'buildings',
  DOCUMENTS: 'documents',
  EVENTS: 'events',
  GROUPS: 'groups',
  GROUP_ORDERS: 'groupOrders',
  ORDERS: 'orders',
  RESERVATIONS: 'reservations',
  RESERVATION_STATUS: 'reservationStatus',
  RESERVATION_SPACES: 'reservationSpaces',
  RV_LOTS: 'rvLots',
  RV_PRODUCTS: 'rvProducts',
  RV_SPOTS: 'rvSpots',
  STALLS: 'stalls',
  STALL_PRODUCTS: 'stallProducts',
  USERS: 'users',
  USER_ROLES: 'userRoles',
  VENUES: 'venues'
};
